name: Deploy to VPS

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List SSH Keys
        run: ssh-add -l

      - name: Add SSH Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2222 yeray.informaticamajada.es >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -tt fana5143@yeray.informaticamajada.es -p 2222 << 'EOF'
            cd /var/www/html/LocalEvents_BackEnd
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate:fresh --seed
            php artisan optimize:clear
            sudo service php8.3-fpm reload
          EOF
