name: Deploy to VPS

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          host: 200.234.231.250
          port: 2222
          username: fana5143
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "
            cd /var/www/html/LocalEvents_BackEnd;
            git stash;
            git pull origin development;
            composer install --no-dev --optimize-autoloader;
            php artisan migrate:fresh --seed --force;
            php artisan optimize:clear;
            npm install;
            npm run build;
            sudo service php8.3-fpm reload;
            "
