name: Despliegue del back-end

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  deploy:
    name: Despliegue en el vps
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: yeray.informaticamajada.es
          port: 2222
          username: fana5143
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "
            cd /var/www/html/LocalEvents_BackEnd;
            git stash;
            git pull origin development;
            composer install --no-dev --optimize-autoloader;
            php artisan optimize:clear;
            npm install;
            npm run build;
            sudo service php8.3-fpm reload;
          "
